### ISSUE TITLE
Building our own flowcharts

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/Unlock#15]
So we can have a complete conversation interaction need to bear in mind any situation covered in the user stories:  
   - [x] Whether they can travel (!) #1 
  - [ ] Consequences of not following the process #3
  - [x] Alternatives #5 

Hopefully if we have a pretty robust flowchart we can add it to the basic logic (#15) relatively easily.

**Comment by Jen-Harris** [comment]
Hey @DebbieSUnlock,
we've built on the flow charts you shared with us yesterday to try and create a full journey for the interaction the user could have with the bot. 
There are points where we direct them to the website or phone, which may not be the best option? 
Please can you have a look and advise if this flow fits with your expectations? 
![image](https://user-images.githubusercontent.com/26116988/32831759-4027ec02-c9f1-11e7-9dc3-8a690f24a7a1.png)

**Comment by DebbieSUnlock** [comment]
Hi @Jen-Harris 

Would you like me to comment on the wording you've used or just the process that you've set out?

**Comment by DebbieSUnlock** [comment]
HI @Jen-Harris 

I'll work my way down the flow-chart and hopefully my comments will make some sense. 

1st Bot interaction - Can we ask a more general question "Would you like advice on travelling abroad".

Where the answer to this is 'No' and Bot directs to the website, will we be providing a link to hub.unlock.org.uk?

On the next line which has the countries, under 'Other' can we direct to the website rather than getting people to call us (http://hub.unlock.org.uk/information/travelling-abroad/)

Under Australia and Canada can we direct to specific website pages - http://hub.unlock.org.uk/knowledgebase/travelling-canada/ or http://hub.unlock.org.uk/knowledgebase/travelling-australia/

Under America can we just provide two options - Live/Work and Holiday (instead of travel).

Under LIve/Work can we then direct to the US Embassy - https://uk.usembassy.gov/visas/visa-information-services/.

If a client answers 'No' to all Bots questions about convictions the result should be 'Great news you can travel on an ESTA. If you need more information you can find it at: http://hub.unlock.org.uk/knowledgebase/travelling-to-the-usa-the-esta-form-and-moral-turpitude/

If a client answers 'Yes' then under 'When are you travelling' can we have:
More than 6 months time
Less than 6 months time

If 'More than 6 months' then the result should be 
'You'll need to apply to the US Embassy for a Visa. You can find more information at http://hub.unlock.org.uk/knowledgebase/travelling-us-need-visa/.

Where we state that you can lie on the ESTA form, could we also give the option to postpone the holiday. 

Just one more thing, under the descriptions of the convictions (for example convicted of a crime that resulted in serious damage to property etc), could we provide a link to some examples of the type of offences that would be covered. 

Hope this is OK. Please let me know if you're confused by my comments.

D

**Comment by Jen-Harris** [comment]
Thanks so much @DebbieSUnlock! I'll make these amendments and share with you again shortly

**Comment by Jen-Harris** [comment]
Hey @DebbieSUnlock,

Please see below the updated flow chart. Is this how you imagined the examples in the flow? If so could you provide examples for each of the questions? 
Included this may be a stretch given the time constraints but we will try our best. 

![image](https://user-images.githubusercontent.com/26116988/32841344-ec128cbe-ca11-11e7-9b5a-25fca0651643.png)

**Comment by Jen-Harris** [comment]
Ignore the one above - some of the routes aren't correct!

**Comment by Jen-Harris** [comment]
_*This one*_ is the correct example @DebbieSUnlock @m4v15  👍 
![image](https://user-images.githubusercontent.com/26116988/32842878-394c14d8-ca16-11e7-91e1-859851103fe3.png)

**Comment by DebbieSUnlock** [comment]
Hi @Jen-Harris 

Thanks for the update.

Where the Bot says 'great news you can travel on an ESTA' it might be good to link to how you'd apply for an ESTA 
http://hub.unlock.org.uk/knowledgebase/travelling-to-the-usa-the-esta-form-and-moral-turpitude/

As far as the examples are concerned, I think we only need to provide examples under the section which says 'Have you ever been convicted of a crime which results in serious damage to property etc etc .... We can take out the example section from the other 3 questions. Sorry. 

Totally understand the time constraints - I'll try and get some examples over to you and we'll just see how much time we have. 

Loving the look and feel of this.

Many thanks

**Comment by Jen-Harris** [comment]
Thanks @DebbieSUnlock, We'll include the information on how to apply for an ESTA
in the flow. 
We should be fine to include one set of examples - just let us know what you want to include and I'll update the flow chart

**Comment by DebbieSUnlock** [comment]
Thanks @Jen-Harris 

Here's a list of the examples 
[CIMT.docx](https://github.com/InFact-coop/Unlock/files/1475287/CIMT.docx)

Hope this is ok.

D

**Comment by Jen-Harris** [comment]
Thanks @DebbieSUnlock. Is there a public link for this as well to include in the flow? 
J

**Comment by DebbieSUnlock** [comment]
Hi @Jen-Harris 

You can find it at http://hub.unlock.org.uk/wp-content/uploads/Annex-A-Crimes-involving-moral-turpitude.pdf

D

**Comment by Jen-Harris** [comment]
@m4v15 ![image](https://user-images.githubusercontent.com/26116988/32890276-f7a67f22-cac5-11e7-87a9-369ba0d3b54f.png)
